# Local server
server:
  port: 8383
  servletPath: /*
  contextPath:

endpoints:
  # For multiple microservices on the same container
  jmx:
    uniqueNames: true

spring:
  jackson:
    mapper:
      DEFAULT_VIEW_INCLUSION: true
  boot:
    admin.url: ${admin.url}
  jmx:
    default-domain: dependencies
  aop:
    proxyTargetClass: true

# Microservices
admin:
  url: http://localhost:8085

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

infinispan:
  config: dependencies-infinispan.xml
