server:
  port: 8383
  contextPath: /dependencies
  # context-path: for spring-boot-admin (AdminClientProperties)
  context-path: /dependencies

spring:
  boot:
    admin.url: http://localhost:8080/admin

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/serviceregistry/eureka/
