server:
  port: 8989
  servletPath: /*
  contextPath:

spring:
  boot:
    admin:
      url: http://localhost:8085
      period: 360000
  jmx:
    default-domain: dependencies
eureka:
  client:
    serviceUrl:
      defaultZone: http://esrvj6d1.web.bc:22141/serviceregistry/eureka/

endpoints:
  jmx:
    uniqueNames: true

